server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/bdd_challenge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/